const categoryData = [
  { name: 'YKS TYT Matematik', slug: 'yks-tyt-matematik' },
  { name: 'YKS TYT Turkce', slug: 'yks-tyt-turkce' },
  { name: 'YKS TYT Fen Bilimleri', slug: 'yks-tyt-fen-bilimleri' },
  { name: 'YKS TYT Sosyal Bilimler', slug: 'yks-tyt-sosyal-bilimler' },
  { name: 'YKS AYT Matematik', slug: 'yks-ayt-matematik' },
  { name: 'YKS AYT Fizik', slug: 'yks-ayt-fizik' },
  { name: 'YKS AYT Kimya', slug: 'yks-ayt-kimya' },
  { name: 'YKS AYT Biyoloji', slug: 'yks-ayt-biyoloji' },
  { name: 'YKS AYT Edebiyat', slug: 'yks-ayt-edebiyat' },
  { name: 'YKS AYT Tarih', slug: 'yks-ayt-tarih' },
  { name: 'YKS AYT Cografya', slug: 'yks-ayt-cografya' },
  { name: 'YKS AYT Felsefe', slug: 'yks-ayt-felsefe' },
  { name: 'YKS AYT Din Kultur', slug: 'yks-ayt-din-kultur' },
  { name: 'LGS Hazirlik', slug: 'lgs-hazirlik' },
  { name: 'KPSS Genel Yetenek', slug: 'kpss-genel-yetenek' },
  { name: 'KPSS Genel Kultur', slug: 'kpss-genel-kultur' },
  { name: 'ALES Hazirlik', slug: 'ales-hazirlik' },
  { name: 'DGS Hazirlik', slug: 'dgs-hazirlik' },
  { name: 'YDS YOKDIL Hazirlik', slug: 'yds-yokdil-hazirlik' },
  { name: 'TOEFL IELTS Hazirlik', slug: 'toefl-ielts-hazirlik' },
  { name: 'Ingilizce Dil Bilgisi', slug: 'ingilizce-dil-bilgisi' },
  { name: 'Ingilizce Konusma', slug: 'ingilizce-konusma' },
  { name: 'Ingilizce Kelime', slug: 'ingilizce-kelime' },
  { name: 'Almanca Ogrenme', slug: 'almanca-ogrenme' },
  { name: 'Fransizca Ogrenme', slug: 'fransizca-ogrenme' },
  { name: 'Arapca Ogrenme', slug: 'arapca-ogrenme' },
  { name: 'Yazilim Gelistirme', slug: 'yazilim-gelistirme' },
  { name: 'Web Gelistirme', slug: 'web-gelistirme' },
  { name: 'Frontend Gelistirme', slug: 'frontend-gelistirme' },
  { name: 'Backend Gelistirme', slug: 'backend-gelistirme' },
  { name: 'Mobil Uygulama Gelistirme', slug: 'mobil-uygulama-gelistirme' },
  { name: 'Python Programlama', slug: 'python-programlama' },
  { name: 'Java Programlama', slug: 'java-programlama' },
  { name: 'C Sharp Dotnet', slug: 'csharp-dotnet' },
  { name: 'JavaScript TypeScript', slug: 'javascript-typescript' },
  { name: 'SQL ve Veritabani', slug: 'sql-ve-veritabani' },
  { name: 'Siber Guvenlik', slug: 'siber-guvenlik' },
  { name: 'Yapay Zeka ve Makine Ogrenmesi', slug: 'yapay-zeka-ve-makine-ogrenmesi' },
  { name: 'Veri Bilimi', slug: 'veri-bilimi' },
  { name: 'Bulut Bilisim', slug: 'bulut-bilisim' },
  { name: 'DevOps ve CI CD', slug: 'devops-ci-cd' },
  { name: 'UI UX Tasarim', slug: 'ui-ux-tasarim' },
  { name: 'Grafik Tasarim', slug: 'grafik-tasarim' },
  { name: 'Canva Sunum Tasarimi', slug: 'canva-sunum-tasarimi' },
  { name: 'PowerPoint Sunum Hazirlama', slug: 'powerpoint-sunum-hazirlama' },
  { name: 'Google Slides Sunum', slug: 'google-slides-sunum' },
  { name: 'Proje Yonetimi', slug: 'proje-yonetimi' },
  { name: 'Isletme ve Yonetim', slug: 'isletme-ve-yonetim' },
  { name: 'Girisimcilik', slug: 'girisimcilik' },
  { name: 'Pazarlama Stratejileri', slug: 'pazarlama-stratejileri' },
  { name: 'Dijital Pazarlama', slug: 'dijital-pazarlama' },
  { name: 'Sosyal Medya Pazarlama', slug: 'sosyal-medya-pazarlama' },
  { name: 'E Ticaret', slug: 'e-ticaret' },
  { name: 'Finans ve Yatirim', slug: 'finans-ve-yatirim' },
  { name: 'Kripto Para ve Blockchain', slug: 'kripto-para-ve-blockchain' },
  { name: 'Kisisel Gelisim', slug: 'kisisel-gelisim' },
  { name: 'Etkili Sunum Teknikleri', slug: 'etkili-sunum-teknikleri' },
  { name: 'Topluluk Onunde Konusma', slug: 'topluluk-onunde-konusma' },
  { name: 'CV Hazirlama ve Kariyer', slug: 'cv-hazirlama-ve-kariyer' },
  { name: 'Mulakat Teknikleri', slug: 'mulakat-teknikleri' },
  { name: 'Saglik Bilimleri', slug: 'saglik-bilimleri' },
  { name: 'Tip Fakultesi Dersleri', slug: 'tip-fakultesi-dersleri' },
  { name: 'Hemsirelik Notlari', slug: 'hemsirelik-notlari' },
  { name: 'Hukuk Ders Notlari', slug: 'hukuk-ders-notlari' },
  { name: 'Psikoloji Ders Notlari', slug: 'psikoloji-ders-notlari' },
  { name: 'Tarih Sunumlari', slug: 'tarih-sunumlari' },
  { name: 'Cografya Sunumlari', slug: 'cografya-sunumlari' },
  { name: 'Felsefe Sunumlari', slug: 'felsefe-sunumlari' },
  { name: 'Din Kultur Sunumlari', slug: 'din-kultur-sunumlari' },
  { name: 'Biyoloji Sunumlari', slug: 'biyoloji-sunumlari' },
  { name: 'Kimya Sunumlari', slug: 'kimya-sunumlari' },
  { name: 'Fizik Sunumlari', slug: 'fizik-sunumlari' },
  { name: 'Matematik Sunumlari', slug: 'matematik-sunumlari' },
  { name: 'Roman ve Edebiyat Incelemesi', slug: 'roman-ve-edebiyat-incelemesi' },
  { name: 'Sanat ve Kultur', slug: 'sanat-ve-kultur' },
  { name: 'Muzik ve Sahne Sanatlari', slug: 'muzik-ve-sahne-sanatlari' },
  { name: 'Mimarlik ve Ic Mimari', slug: 'mimarlik-ve-ic-mimari' },
  { name: 'Muhendislik Dersleri', slug: 'muhendislik-dersleri' },
  { name: 'Elektrik Elektronik', slug: 'elektrik-elektronik' },
  { name: 'Makine Muhendisligi', slug: 'makine-muhendisligi' },
  { name: 'Insaat Muhendisligi', slug: 'insaat-muhendisligi' },
  { name: 'Endustri Muhendisligi', slug: 'endustri-muhendisligi' },
  { name: 'YKS TYT Geometri', slug: 'yks-tyt-geometri' },
  { name: 'YKS TYT Problem Cozumleri', slug: 'yks-tyt-problem-cozumleri' },
  { name: 'YKS AYT Geometri', slug: 'yks-ayt-geometri' },
  { name: 'YKS AYT Integral', slug: 'yks-ayt-integral' },
  { name: 'YKS AYT Trigonometri', slug: 'yks-ayt-trigonometri' },
  { name: 'LGS Matematik', slug: 'lgs-matematik' },
  { name: 'LGS Fen Bilimleri', slug: 'lgs-fen-bilimleri' },
  { name: 'LGS Turkce', slug: 'lgs-turkce' },
  { name: 'LGS Inkilap Tarihi', slug: 'lgs-inkilap-tarihi' },
  { name: 'KPSS Egitim Bilimleri', slug: 'kpss-egitim-bilimleri' },
  { name: 'KPSS Alan Bilgisi', slug: 'kpss-alan-bilgisi' },
  { name: 'YDS Kelime Ezber', slug: 'yds-kelime-ezber' },
  { name: 'IELTS Speaking', slug: 'ielts-speaking' },
  { name: 'TOEFL Writing', slug: 'toefl-writing' },
  { name: 'SAT Hazirlik', slug: 'sat-hazirlik' },
  { name: 'GRE Hazirlik', slug: 'gre-hazirlik' },
  { name: 'React NextJS', slug: 'react-nextjs' },
  { name: 'NodeJS Express', slug: 'nodejs-express' },
  { name: 'NestJS Mikroservis', slug: 'nestjs-mikroservis' },
  { name: 'PHP Laravel', slug: 'php-laravel' },
  { name: 'Go Programlama', slug: 'go-programlama' },
  { name: 'Rust Programlama', slug: 'rust-programlama' },
  { name: 'Data Structures Algorithms', slug: 'data-structures-algorithms' },
  { name: 'System Design', slug: 'system-design' },
  { name: 'Clean Code Yazilim Mimarisi', slug: 'clean-code-yazilim-mimarisi' },
  { name: 'Test Otomasyonu', slug: 'test-otomasyonu' },
  { name: 'Selenium Playwright', slug: 'selenium-playwright' },
  { name: 'Docker Kubernetes Ileri', slug: 'docker-kubernetes-ileri' },
  { name: 'Linux Sistem Yonetimi', slug: 'linux-sistem-yonetimi' },
  { name: 'Network Temelleri', slug: 'network-temelleri' },
  { name: 'Ethical Hacking Pentest', slug: 'ethical-hacking-pentest' },
  { name: 'AI Prompt Engineering', slug: 'ai-prompt-engineering' },
  { name: 'Generative AI Uygulamalari', slug: 'generative-ai-uygulamalari' },
  { name: 'LLM RAG Mimarisi', slug: 'llm-rag-mimarisi' },
  { name: 'Business Analytics PowerBI', slug: 'business-analytics-powerbi' },
  { name: 'Excel Ileri Seviye', slug: 'excel-ileri-seviye' },
  { name: 'SQL Sorgu Pratikleri', slug: 'sql-sorgu-pratikleri' },
  { name: 'Veri Gorsellestirme Tableau', slug: 'veri-gorsellestirme-tableau' },
  { name: 'Product Management', slug: 'product-management' },
  { name: 'Growth Marketing', slug: 'growth-marketing' },
  { name: 'SEO ve Icerik Stratejisi', slug: 'seo-ve-icerik-stratejisi' },
  { name: 'Google Ads Reklamciligi', slug: 'google-ads-reklamciligi' },
  { name: 'Meta Ads Reklamciligi', slug: 'meta-ads-reklamciligi' },
  { name: 'YouTube Icerik Uretimi', slug: 'youtube-icerik-uretimi' },
  { name: 'Online Kurs Hazirlama', slug: 'online-kurs-hazirlama' },
  { name: 'Ogretmenler Icin Dijital Sinif', slug: 'ogretmenler-icin-dijital-sinif' },
  { name: 'Universite Ders Notlari', slug: 'universite-ders-notlari' },
  { name: 'Tez Yazim ve Akademik Arastirma', slug: 'tez-yazim-ve-akademik-arastirma' },
  { name: 'Etkili Not Tutma ve Hafiza', slug: 'etkili-not-tutma-ve-hafiza' },
  { name: 'Zaman Yonetimi ve Verimlilik', slug: 'zaman-yonetimi-ve-verimlilik' },
];

module.exports = { categoryData };
